# This action enables building the executables for cli, can be triggered manually or by release creation.
name: discord

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  executables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: |
          echo "successful"


